= Report
#enum(
  start: 1,
  spacing: 1.1em,
  tight: false, 
  numbering: n => text(    
    numbering("1.", 24-n+1),
  ),	
[Lix, Lisa Marie and Smith, Mark and Pitz, Marshall and Ahmed, Rashid and Quon, Harvey and Griffith, Jane and Turner, Donna Ranneris and Hong, Say and Prior, Heather Jane and Banerjee, Ankona and others._Cancer data linkage in Manitoba: expanding the infrastructure for research_* (2016)* .],
[NicAmhlaoibh, Roisin and Mahmud, Salah and Comber, Harry._Patterns of care and survival from cancer in Ireland 1994 to 1998_* (2004)* .],
[Monchka B [V] and Zhang G [V] and Righolt C [V] and Mahmud SM._The epidemiology, outcomes and social and economic burden of mood disorders in Manitoba: A data-linkage retrospective cohort study_* (2018)* .],
[Righolt C [V] and Mahmud SM._Patterns, Predictors and Outcomes of Empiric Anti-bacterial Therapy for Complicated Pulmonary, Urinary Tract and Intra-abdominal Infections in Manitoba Hospitals: A Record-Linkage Study_* (2017)* .],
[Mahmud SM and Pabla G [V] and Righolt CH [V]._The Direct Medical costs of Diseases Associated with Human Papillomavirus Infection in Manitoba, Canada_* (2017)* .],
[Righolt CH [V] and Gieni RS [V] and Bozat-Emre S [S] and Mahmud SM._Effectiveness of the human papillomavirus vaccination program against cervical dysplasia in Manitoba, Canada_* (2017)* .],
[Mahmud S and Bozat-Emre S [S] and Jha S and Mostaco-Guidolin LC [S]._Vaccine Safety, Effectiveness \&amp; Uptake in Manitoba: The Background Incidence Rate Project, Disease Background Incidence Rates and Assessment of Vaccine-related Adverse Events_* (2016)* .],
[National Advisory Committee on Immunization (NACI)._Statement on Seasonal Influenza Vaccine for 2015-2016_* (2015)* The University of Manitoba, Manitoba, Canada.http://www.phac-aspc.gc.ca/naci-ccni/flu-2015-grippe-eng.php..],
[Plourde P and Reimer J and Marshall S and Ross C and Bailey K and Mahmud S and Green C and Nowicki D [V] and Whitlock M [V] and Shaw S._Evaluation of HIV Surveillance Winnipeg Health Region, 2011_* (2014)* Winnipeg Regional Health Authority, Manitoba, Canada..],
[Mahmud S and Kliewer E and Ronald A and Law B._The Safety of GSK Biological's H1N1 Pandemic Vaccine in Manitoba, Canada_* (2013)* .],
[Plourde P and Reimer J and Marshall S and Ross C and Bailey K and Mahmud S and Green C and Nowicki D [V] and Whitlock  M [V] and Shaw S._The Epidemiology of Human Immunodeficiency Virus (HIV) in the Winnipeg Health Region, 2010-2012_* (2013)* Winnipeg Regional Health Authority, Manitoba, Canada..],
[Mahmud S and Bozat-Emre S [S] and Mostaço-Guidolin L [S] and Tennakoon A and Strome T._The Utility of Emergency Department Data for the Early Detection of Adverse Events Following Vaccinations during Mass Immunization Campaigns_* (2013)* .],
[Mahmud S and Kliewer EV and Lambert P and Bozat-Emre S [S] and Demers A and Templeton K._Effectiveness of the Quadrivalent Human Papillomavirus Vaccine against Cervical Abnormalities in Manitoba, Canada_* (2012)* CancerCare Manitoba, Manitoba, Canada..],
[Kliewer E and Mahmud SM and Demers A and Lambert P and Musto G._Human Papillomavirus Vaccination and Anogenital Warts in Manitoba_* (2012)* CancerCare Manitoba, Manitoba, Canada..],
[Whitlock M [V] and Shaw S and Nowicki D [V] and Mahmud S._The epidemiology of active tuberculosis disease in the Winnipeg Health Region, 2009-2011_* (2012)* Winnipeg Regional Health Authority, Manitoba, Canada..],
[Kliewer EV and Mahmud S and Demers AA and Lambert P and Templeton K and Harrison M._Human Papillomavirus Vaccination and Cervical Cancer Screening in Manitoba_* (2012)* CancerCare Manitoba, Manitoba, Canada..],
[Demers A and Mahmud SM._The epidemiology of pandemic H1N1 influenza A virus in Manitoba, 2010_* (2010)* Winnipeg Regional Health Authority, Manitoba, Canada..],
[Whitlock M [V] and Shaw S and Nowicki D [V] and Mahmud SM._The epidemiology of pandemic H1N1 influenza A virus in the Winnipeg Health region, 2009_* (2010)* Winnipeg Regional Health Authority, Manitoba, Canada..],
[Mahmud S and Comber H and Reilly M._Cancer in Ireland, 1994 to 1998.  Incidence, Mortality, Treatment and Survival. Report of the National Cancer Registry_* (2003)* .],
[NicAmhlaoibh R and Mahmud S and Comber H._Patterns of care and survival from cancer in Ireland 1994 to 1998_* (2003)* .],
[Reilly M and Salim A and Mahmud S._Software tools for optimal two-stage sampling: a user guide_* (2003)* .],
[Mahmud S._The final report of The Arab Libyan Maternal and Child Health Survey-the Pan Arab Project for Child Development (PAPCHILD) - The Arab League (in Arabic 1997, in English 1998)_* (1998)* .],
[Mahmud S._Effects of parent's education on children's language, fine-motor adaptive, gross motor and personal-social development in Porte Alegre, Brazel. MSc Dissertation (MSC 2473)_* (1998)* .],
[Mahmud S._A guide to costing blood transfusion services WHO Blood Safety Unit, Geneva_* (1998)* World Health Organization, Switzerland..],
)
